/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.kevcodez.gotrue

import kotlin.test.Test

class GoTrueClientTest {
    @Test
    fun testSomeLibraryMethod() {
        val apikey = ""

        val classUnderTest = GoTrueClient("https://eyimuvrqyphojiqwapfv.supabase.co/auth/v1", mapOf(
                "apiKey" to apikey,
                //"Authorization" to "Bearer $apikey"
        )
        )

        val token = classUnderTest.token(
                grantType = "password", email = "k.grueneberg1994@gmail.com", password = "foobar")
        println(token)

        val user = classUnderTest.getUser(token.accessToken)
        println("fasd")

        classUnderTest.updateUser(accessToken = token.accessToken, data = mapOf("foo" to "bar"))

        classUnderTest.logout(token.accessToken)
    }
}
